### PR TITLE
WIP: Use strato as os-base base image

### PR DESCRIPTION
**Pull request by joshwget**
[strato](https://github.com/joshwget/strato) is a small image based on glibc with a containerized build process for packages.

Using `strato-min` rather than `strato` as the base image for now. The only difference is that `strato-min` doesn't actually include the strato binary. It's fairly large and doesn't add much value to the base image for now.

This increases ISO size by about 2mb, but I think most of this is a result of switching from uclibc to glibc. It's likely that a lot of optimizations can be made still.

The only work remaining is testing and multiarch support. I'm nearly done with the arm64 port of strato and I don't expect the arm port to be much work beyond that.

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
wow....

**Comment by ibuildthecloud** [comment]
Still don't like the name.

**Comment by deniseschannon** [comment]
still better than the original name...

**Comment by SvenDowideit** [comment]
@joshwget I wonder how this will affect @tetatetit 's LUK https://github.com/rancher/os-base/pull/39

it might make it simpler?

**Comment by joshwget** [comment]
@SvenDowideit Once the associated packages are added to strato it should make it easier. Modifying os-base to include a few new strato packages should be much more straightforward than having to configure buildroot.

The really nice thing is that we'll be able to make use of layers with strato. buildroot just produces a fixed set of packages that can't be changed once it's built. In other words, you'd be able to do something like the following.

```
FROM os-base
RUN strato add ...
```

**Comment by tetatetit** [comment]
> @joshwget I wonder how this will affect @tetatetit 's LUK rancher/os-base#39
> it might make it simpler?

Yep, apparently, since:
1. cryptsetup crashes on uclibc and this is confirmed problem so my must to switch back to glibc in my work.
2. buildroot misses [thin-provisioning-tools](https://github.com/jthornber/thin-provisioning-tools) for lvm thin provision state partition which could be quite useful in case btrfs is not the base choice (e.g. for high loaded mysql, postgresql, [rancher vm](https://github.com/rancher/vm) but anyway snapshotting capabilities are necessary (e.g. for [convoy](https://github.com/rancher/convoy) or for custom live volume backup like e.g. mine duplicity based to OneDrive) keeping disk storage optimal and flexible for managemrnt at the same time
3. buildroot misses zfs tools for state partition and zfs out of the box, while it is relatively easy to include zfs in rancher kernel build process (almost done this, but just forced to switch to higher priority tasks). That is why I started to consider switched os-base to alpine and how with [strato](https://github.com/joshwget/strato) it is easiest, most organized and maintenable way to do IMO since 

But so far I understand [strato](https://github.com/joshwget/strato) uses ubuntu right now as base image for it packages with is 128M size itself only (while plus other packages required for os-base). So I suggest to switch to alpine there to keep initrd size close (if not smaller) thant current buildroot based.

**Comment by joshwget** [comment]
@tetatetit strato uses the Ubuntu image only to build packages and it doesn't actually use Ubuntu as a base image. Alpine, buildroot, and strato all end up being around the same size when used for os-base.

**Comment by joshwget** [comment]
Added iptables for #1362. Could be done in a follow up PR, but I don't see much harm in including it here.

**Comment by tetatetit** [comment]
Ah, sorry that did not take deeper into strato. Now I see it just does `wget; cd; make; ./configure` from source for each package and then build it into docker image...so trivial and so brilliantly :). So it can be package src from official (as it is now), from Alpine src disstro, from buildroot or whatever else tiny of best choice. So yes it apparently help me a lot regardless if buildroot or alpine will be chosen! But in case of buildroot we should switch back to glibc due of resons stated above and in that my PR

**Comment by tetatetit** [comment]
Just I would suggest better to try alpine since it is wider used then buildroot and therefore better tested IMO, plus have bigger community for the case of some issue. E.g. alpine used as variant of base image for lot of official docker images (e.g. php) as well as included as base image from some cloud provider (e.g. growing French bare metal www.scaleway.com)

**Comment by joshwget** [comment]
@tetatetit I think you're still viewing strato a little different from what it actually is. It doesn't supplement an existing base image but rather is a base image itself. strato builds a base image from ground up and just happens to reuse Ubuntu to build its packages (for now, at least).

I should put some more work into the README so it's clear what it actually is.

**Comment by tetatetit** [comment]
@joshwget, so far I understand and see - strato uses Dockerfile instructions to build packages from their original official sources, i.e. unmodified, unpatched, similarly like builroot root does but just Dockerfile instructions much more clear and obvious (at least for me) than buildroot package instructions. Is my visio totally correct here? When I mentioned ubuntu or alpine - I meant the same Dockerfile instructions can be used to build packages from source packages of distro of choise. Although what I already though and about to try - just to create os-base image from just docker alpine image during rancher initrd build process, elimiating buildroot at all. Honestly speaking I can not understand (may be somebody will point me better)  what are advantages of buildroot or other image based on just original official source packages over e.g. widely well tested and used alpine with same or even smaller size.

**Comment by SvenDowideit** [comment]
I'm going to play with it a little - so replacing this PR with #1840

**Pull request closed without merging**
