### PR TITLE
Create home dir

### PR DESCRIPTION
**Pull request by juliengk**

### CODE REVIEW

**Comment by SvenDowideit** [comment]
can you squash and rebase please? otherwise, yup LGTM

**Comment by juliengk** [comment]
done :)

**Comment by SvenDowideit** [comment]
weird - didn't I merge the log PR? (or maybe you needed to fetch before the rebase?)

**Comment by juliengk** [comment]
yep weird. i fixed it, should be ok now

**Comment by SvenDowideit** [comment]
I should probably stop merging these code cleanups until I make an v0.8 branch :)

**Pull request merged**
