### PR TITLE
Random fixes

### PR DESCRIPTION
**Pull request by ibuildthecloud**

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
@imikushin Obviously don't merge as there are test failures.  I'm looking into it.

**Comment by ibuildthecloud** [comment]
@imikushin Build is green now.

**Comment by imikushin** [comment]
Looks fine except one comment above.

**Comment by imikushin** [comment]
LGTM

**Comment by deniseschannon** [comment]
https://github.com/rancher/os/issues/731

**Comment by deniseschannon** [comment]
https://github.com/rancher/os/issues/675

**Pull request merged**
