### PR TITLE
Avoid kernel too old error when building ROS

### PR DESCRIPTION
**Pull request by niusmallnan**
https://github.com/rancher/os/issues/2037
https://github.com/rancher/os/issues/2414
https://github.com/rancher/os/issues/1992

### CODE REVIEW

**Comment by segator** [comment]
still happens 
Host Kernel: 4.14.32-rancher2
RancherOS Kernel: 4.14.32-rancher3
Your host kernel must be greater than RancherOS KERNEL_VERSION
FATA[0263] exit status 1
Makefile:11: recipe for target 'default' failed

**Comment by niusmallnan** [comment]
Hi @segator ,
That is the result I expect.
This is to prompt the user to compile with the correct kernel version in advance.

**Comment by liyimeng** [comment]
hi @niusmallnan could please elaborate why do you make such enforcement? can it be >= instead of >?

**Comment by niusmallnan** [comment]
@liyimeng You can use `KERNEL_CHECK=0 make`.

**Comment by liyimeng** [comment]
Thanks @niusmallnan!  I read the reason in another page

**Pull request merged**
