### PR TITLE
Elide cmdline

### PR DESCRIPTION
**Pull request by SvenDowideit**
this should be merged after #1666 - the last commit is the only new change.

also requires https://github.com/rancher/os-kernel/pull/48

this is for #1537 - @janeczku

### CODE REVIEW

**Comment by janeczku** [comment]
@SvenDowideit need to obtain customer feedback

**Comment by janeczku** [comment]
@SvenDowideit need clarification. Given a cmdline:
```
kernel ${base-url}/vmlinuz rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda] -- rancher.cloud_init.datasources=[url:http://example.com/cloud-config]

**Comment by SvenDowideit** [comment]
@janeczku It will need to be stored in the `ros config` - would they prefer all in one single string, or as an array? (i don't think we can do it as a tree)

**Comment by janeczku** [comment]
@SvenDowideit 

> ok - as a proposal - what if we added the elided cmdline parts as a string to rancher.environment.CMDLINE_EXTRA - that way it can be added to services 

Does that work with ad-hoc (cloud-config) services? If yes then this would be definitely helpful for them.

**Comment by SvenDowideit** [comment]
excellent (yes, I think the environment key works for both in os-config and service.yml based services - the only pain would be using `system-docker run`

**Comment by SvenDowideit** [comment]
next up, a test and doc example of how to get the `EXTRA_CMDLINE` into a service using the environment

**Comment by SvenDowideit** [comment]
ok, I'm going to merge this for 0.9.0-rc2 so we can try it out.

**Comment by janeczku** [comment]
@SvenDowideit I don't think `rancher.environment` k/v are passed to the console service environment currently. Do you think it makes sense though?

**Comment by SvenDowideit** [comment]
IDK - is there a reason why we'd want the non-root user in the console to access this information by default?

**Comment by janeczku** [comment]
@SvenDowideit yeah better to leave the current behavior not setting it in the container env.

**Pull request merged**
