### PR TITLE
Add some info about creating console images

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

docs to go with 

https://github.com/rancher/os-images/pull/108
https://github.com/rancher/os-services/pull/51

for 

https://github.com/rancher/os/issues/1151

### CODE REVIEW

**Comment by joshwget** [comment]
LGTM. Not that it really matters much for docs, but I think CI is failing because you need to rebase.

**Comment by SvenDowideit** [comment]
@deniseschannon :)

**Comment by deniseschannon** [comment]
Are we going to make this one of the options in `ros console list`? if so, shoudln't we update

http://docs.rancher.com/os/configuration/custom-console/

**Comment by joshwget** [comment]
@SvenDowideit Can you rebase? Definitely looking forward to merging this :smile:

**Comment by deniseschannon** [comment]
Before merging, can @SvenDowideit add in docs here:

https://github.com/rancher/os/blob/master/docs/os/configuration/custom-console/index.md

**Comment by SvenDowideit** [comment]
@deniseschannon :)

**Pull request merged**
