### PR TITLE
Add support for booting live iso off of EFI

### PR DESCRIPTION
**Pull request by deitch**
Uses Rod Smith's rEFIt boot manager and enables ability to boot live iso on system with UEFI/EFI firmware without legacy support mode (CSM).

This PR is as requested by @ibuildthecloud see #844.

Several points:

1. To test, launch in virtual box, under Settings -> System, check "EFI"
2. Once launched, log in as usual (rancher/rancher), and see that the directory `/sys/firmware/efi/` exists. This only is created by the Linux kernel when the system was booted EFI.
3. This does not install EFI-bootable when installed to local disk `ros install`. Once this PR is accepted and merged, I will look at adding that capability.

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
@deitch This is really cool.  It will take me a bit before I can review it in depth and merge it but it definitely seems like a good approach.  Random question, our ISO can also be used as a USB stick, by chance does this work the same way with EFI?

**Comment by deitch** [comment]
It should work the same way, since you are building a hybrid iso. But I can easily check it.

There are a few remaining issues:

1. Initial boot has a startup delay. It gets to the EFI loader, then sits for ~30 seconds before starting the kernel. Better 30 seconds than no EFI support at all, and that is fixable if I can find the time.
2. I want to get `ros install` to install with EFI support as well. The problem is that plain `ros install` doesn't work with plain v0.5! I am going to open another issue.
3. Plain build fails with v0.5 because of image tagging issues. See #936 
4. Validate USB

I will take care of the 4th on the list; please check 2 & 3.

**Comment by joshwget** [comment]
Two small things:
1. I think `efi.txt` would be better off in our docs, rather than in the root of the project
2. These two commits seem related, so perhaps they should be squashed?

Thanks for the contribution! :smile:

**Comment by deitch** [comment]
@joshwget 

> 1. I think efi.txt would be better off in our docs, rather than in the root of the project

Yes, good idea. I am not convinced it needs to be kept, but I think given the history of non-EFI, having one place that says, "this is how you get EFI to work" is a good idea. 

Give me the pointer to where the docs repo is and I will move it there?

> 2. These two commits seem related, so perhaps they should be squashed?

Oops. Yes, they were supposed to and I forgot. I started work on my (very old) macbook air, realized the build was killing it, so committed to my own repo, then pulled to an alternate Ubuntu laptop I have next to it. Added necessary changes, then committed those, meant to squash them.... and completely forgot! :-)

> Thanks for the contribution! :smile:

:smile:

**Comment by deniseschannon** [comment]
@deitch Our docs are all located at https://github.com/rancher/rancher.github.io

PRs are always welcome :)

**Comment by deitch** [comment]
@joshwget squashed the commits. OK, I admit it; I had to look at the git manual to remember how to do it (`git reset --hard HEAD~2 && git merge --squash HEAD{1} && git commit && git push origin +v0.5`).

**Comment by deitch** [comment]
@deniseschannon where should it go in the docs? There doesn't seem to be a clean, clear place for it.

**Comment by ibuildthecloud** [comment]
@deitch sorry about points 2 and 3, v0.5 is very much a work in progress and those are two of many issues as to why we haven't merged to master.

**Comment by deitch** [comment]
@ibuildthecloud other issue https://github.com/rancher/os/issues/942

**Comment by deitch** [comment]
@ibuildthecloud oops, crossed wires. I didn't realized you had commented. Isn't it 10:30pm in CA? You are making me look bad! ;-)

OK, well, you have the issues open now. I worked around point 3 with manual tagging and got EFI boot to work. Once you have `ros install` - which shouldn't be that hard, since the scripts are already in the `rancher/os` repo - I will try to find some time to get install to EFI to work. I know how, but only so much time I can slice off to volunteer help.

Now, if you could support Secure Boot and encrypted filesystems (root and data)... heh, I just did a major project for a client providing exactly that, plus Intel TXT trusted boot. Was a beast to solve, but at least in my head now.

**Comment by ibuildthecloud** [comment]
@deitch Can't say i'm an expert in secure boot.  If you could give me a high level rundown of what it would take to support it, I'd love to try.

**Comment by deitch** [comment]
Unfortunately, the implementation details are nasty, and there are a lot of over-complications. The short form is that if SecureBoot is enabled, then BIOS has a public key built into it with which it checks the bootloader (isolinux or refind.efi or whatever). If the bootloader (or kernel, if it goes direct, which EFI can) is signed by a key that matches that certificate, then it boots, else it prevents it.

In truth, there are different kinds of certs, and whitelists/blackllists, and chains of multiple certs, but that is the basic idea.

Separate note: the slow booting actually was an issue with virtualbox's EFI implementation, so scratch that.

**Comment by deitch** [comment]
Please do not merge this in yet. Turns out I missed something. It was succeeding only because some EFI implementations have an iso9660 driver built in (my luck, the ones I was testing against have it), but not all do (even most do not), so the boot would fail. I got it working now using grub2 efi instead of rEFInd, but the change for rEFInd should be small. I will merge in one more commit soon.

**Comment by deitch** [comment]
I had to give up on rEFInd. Unfortunately, rEFInd does not support booting an iso9660 (CD filesystem) from within the El Torito boot image.

grub2 does, so I am converting to using that instead, but straight boot. 

I am having one problem, though. It successfully boots, but when it does, it does not accept rancher as the password. Here is my grub line. Any ideas?

````
menuentry "Rancher" {
    set gfxpayload=keep
    linux /boot/vmlinuz quiet rancher.password=rancher rancher.state.autoformat=[/dev/sda,/dev/vda]
    initrd /boot/initrd
}
````

I just took them straight from the isolinux.cfg that was there.

Any way to check that once booted?

Separately, have you ever tried booting rancheros with qemu? I get a kernel panic (booting BIOS or UEFI, doesn't matter).

**Comment by joshwget** [comment]
Do you mind filing a separate issue for the kernel panic? We use QEMU for development and testing, but I can take a look at what's happening in your case.

**Comment by deitch** [comment]
@joshwget sure. I have no issues on vbox, only qemu (I have been trying both). Do you mind sharing your startup line here? e.g. `qemu-system-x86_x64 -cdrom path/to/rancheros.iso`. Do you use any other settings or options?

**Comment by deitch** [comment]
Ah. It appears none of the command-line options is being passed to the kernel. I do not know why, but we will get it.

And then I really need to move back to my actual projects. :-)

**Comment by deitch** [comment]
All done and clean. I think we could make the EFI part smaller, but there is some strange grub bug (say that 10 times quickly!). In the meantime, this is confirmed to work.

Go ahead, merge in!

Once someone takes care of the `ros install` issue #942 , we can get "install to disk with EFI" working.

**Comment by deitch** [comment]
Hey @joshwget and @ibuildthecloud you merging this in? I put in the effort _gratis_, at least should see it get merged in.

**Comment by pwFoo** [comment]
@deitch 
I think your PR will be merged after they take a look at the changes. So be patient. I try to be patient, too *g*

Thanks for your PR!!!

**Comment by deitch** [comment]
> So be patient. I try to be patient, too

You'd think by now I would have learned that! :-)

Funny, as I think about it, when I complete work for a client, I am much more patient. I still want to see it used, but they got what they paid for. When it is a contribution, the personal value is in the usage. It is all about psychology in the end, isn't it? I am laughing at myself now.

OK, I will look for the update. And when someone gets the other issue about `ros install`, I will be try to find time to add it to disk installed.

By the way, @ibuildthecloud, I did a write up on resin.io today, their OS design is very similar.

**Comment by pwFoo** [comment]
@deitch 
A friend created me an iso with your patch, but it doesn't work. I can't boot it up with my Surface Pro 4 with needs EFI boot sticks. 
Rufus says "ISO isn't EFI bootable".

Could You provide me an working ISO with your modifications for testing?

**Comment by pwFoo** [comment]
Tested other ISOs and it only works as GPT partitionscheme for UEFI...
But I don't know that have to be done to make it EFI bootable like gparted, RemixOS or Debian that way...

**Comment by deitch** [comment]
@pwFoo :

> Tested other ISOs and it only works as GPT partitionscheme for UEFI...

I assume you are booting a flash drive? GPT partition scheme doesn't make any sense In the context of a cd/iso, since those are always iso9660/rock ridge (with El Torito boot).

I don't have access to a Surface; what do you get when you boot it?

**Comment by deitch** [comment]
Also, do you have access to a regular laptop with qemu or another emulator *not* VirtualBox; VBox has a built-in iso9660 driver in its UEFI firmware, so it is capable of getting past issues that would stop "normal" firmwares.

If you do, please boot it both as removable iso and as a USB. Like to see what messages you are getting.

**Comment by deitch** [comment]
Hmm, you know? Hold on, I think I was able to replicate it. Looking

**Comment by deitch** [comment]
It gets stranger. The 4 tests cases are CD BIOS, CD UEFI, USB BIOS, USB UEFI. I then tried it on 2 different emulation platforms, qemu and vbox.

**qemu**

* CD BIOS : works
* CD UEFI : works
* USB BIOS : works
* USB UEFI : works

**vbox**

* CD BIOS : works
* CD UEFI : works
* USB BIOS : works
* USB UEFI : **fails**

Even stranger, I have a simple test build, which doesn't go through the whole rancheros build, just builds a simple ISO that boots to a grub menu. The actual making of the iso (for BIOS and UEFI, CD and USB) is just `scripts/package-iso` copied over and slimmed down. It is the identical iso-creation process.

Yet, my slimmed down build works for all test cases in *both* vbox *and* qemu.

**Comment by pwFoo** [comment]
I haven't any knowledge with UEFI / EFI, but the Surface Pro4 doesn't support BIOS / MBR based boot, only "native UEFI / EFI boot". EFI bootable ISO could be written as 
1. BIOS MBR 
1. BIOS EFI
1. UEFI GPT partition

Just the last option works for me / Surface Pro.
Each works fine with a Dell notebook.

**Comment by deitch** [comment]
It actually is easy to write an img file that is just UEFI GPT, or one that is BIOS MBR, or even one that is both. When it is a CD, it becomes a bit trickier, but still OK.

But we are doing a hybrid: iso that is both CD and USB, both UEFI and MBR. 

For the life of me, I am stumped; I have 2 almost identically built images, one boots with all firmwares and all types, the other boots all firmwares and all formats in one emulator, but fails just as UEFI USB on vbox (and therefore likely other firmwares, like your Surface Pro).

Is it possible that something in your firmware doesn't allow *any* hybrid boot? Try downloading the latest ubuntu 16.04 server img, install that on a USB drive, and see if you can boot that?

**Comment by pwFoo** [comment]
Ubuntu or gparted from usb created by Rufus for GPT / UEFI  works fine.

**Comment by deitch** [comment]
> Ubuntu or gparted from usb created by Rufus for GPT / UEFI works fine.

OK, good. I have that test iso that was built using the almost identical process to rancheros iso. I am able to boot it everywhere. I will upload it somewhere; can you download it and try that as well?

**Comment by deitch** [comment]
That should prove that it is the same issue, and then I can try to find time to dig out the difference between rancheros.iso (failing) and testos.iso (working).

Didn't quite know it would be so much work when I started... probably should have guessed. :-)

**Comment by deitch** [comment]
iso is at is https://file.io/ZToOVe

For safety: 

````
# Linux
$ md5sum testos.iso
32afe6aed18664bc3edc231d374bcbf8

# Mac
$ md5 testos.iso
32afe6aed18664bc3edc231d374bcbf8
````

**Comment by deitch** [comment]
To clarify, I made the testos.iso image small at 14MB. It is missing an initrd. I don't care that you can boot a kernel (you can't), only that you can get as far as a functional grub menu. I believe the only choice is "Linux", but as long as you can get past the EFI firmware and into grub, then it works.

**Comment by pwFoo** [comment]
@deitch 
Download doesn't work.

> {"success":false,"error":404,"message":"Not Found"}

**Comment by deitch** [comment]
Huh, it must be time-limited. I wonder if github will let me attach it here. I will try.

**Comment by deitch** [comment]
Well, it did let me. See if you can download it. I had to zip it. Just unzip and then use the enclosed testos.iso

[testos.zip](https://github.com/rancher/os/files/299014/testos.zip)

**Comment by pwFoo** [comment]
Thanks! testos.zip works fine! Boots to a grub shell at my Surface Pro 4! :)
Any changes done since I reported my problem?

**Comment by ibuildthecloud** [comment]
@pwFoo I'm buying a surface if you can get RancherOS running on it.

**Comment by deitch** [comment]
@ibuildthecloud I think I will swing by the Rancher office next time I am in Silicon Valley and abscond with it! :-)

**Comment by deitch** [comment]
@pwFoo I believe that confirms that the difference I am seeing between the 2 images is the same as you are seeing. Now if only we could figure out what the source of the difference is....

**Comment by deitch** [comment]
@pwFoo:

> Any changes done since I reported my problem?

No. That is the really strange thing. The build process is nearly identical for testos.iso and rancheros.iso. I have the exact same issue with vbox (no problems with qemu): testos.iso boots, vbox does not recognize it as a hard drive (find as an optical drive). I am on the verge of opening up the iso in hexedit...

The problem is that firmware - even in a virtual environment like vbox - tends to be closed and opaque. There is nearly no way to get it to tell you:

1. I found a disk
2. I found a GPT
3. GPT says there is an EFI System Partition at sector 256 through sector 8255
4. I tried to read the ESP as FAT32, and it worked
5. I found EFI/BOOT/BOOTX64.EFI on the partition
6. Successfully loaded the BOOTX64.EFI 

Those are, essentially, the steps. When I boot into the UEFI shell, I don't even see it as a filesystem, which means it isn't even getting to step 4: recognized filesystem on a recognize partition.

**Comment by deitch** [comment]
I stand corrected. The problem is **not** the build. The problem was my vbox configuration. (sheepish grin)

Both testos.iso *and* rancheros.iso boot correctly: in vbox and qemu; as optical drive or as hdd/usb; BIOS and UEFI. I also was able to get my laptop - Dell Latitude 6320 - to boot physically from both testos.iso *and* rancheros.iso on a USB drive. 

The question now is why Surface Pro will not boot off of rancheros. Is there anything special or unique required for Surface Pro's firmware? The process of building the iso is identical.

**Comment by deitch** [comment]
@pwFoo I just reread your comments. Did you not succeed in booting the rancheros.iso off of a USB? Or did you not even get far enough to do it because rufus didn't let you get there?

**Comment by pwFoo** [comment]
@deitch 
Could you upload your rancheros iso for testing?
Maybe our build is wrong... I'll test it again with our and your iso to compare.

**Comment by deitch** [comment]
> Could you upload your rancheros iso for testing?

Sure. Will attach in a few mins. 

I just tried using rufus for the first time and had no problems with either iso. Rufus is quite content with them, and they boot. 

Are you doing it in dd mode or iso mode? Rufus offers both.

All my previous builds were all straight dd to get to the USB, since the iso has the filesystem, MBR and GPT on it. Rufus by default (iso mode) tries to open the iso, copy the files and then create its own MBR, GPT, etc.

Did you use it dd only?

**Comment by deitch** [comment]
Here is the link to rancheros.iso. It is only downloadable once; file.io deletes it after first download. I wanted to attach it here, but github puts a file size limit of 10MB.

https://file.io/ML9N9S

Let me know about this iso, and about the dd vs iso format.

Maybe you want to just use dd directly?

**Comment by pwFoo** [comment]
> {"success":false,"error":404,"message":"Not Found"}

I was to late to get it...

**Comment by deitch** [comment]
Try this dropbox link 

https://dl.dropboxusercontent.com/u/5667153/rancheros.iso

**Comment by pwFoo** [comment]
Thanks. Downloaded and start testing with Rufus / DD

**Comment by pwFoo** [comment]
Boot sucessfully your ISO @ Surface! Thanks for sharing!

Bug seems to be related to our ISO build with your modifications from the PR here. We try to build our own ISO with desktop kernel support again.

**Comment by deitch** [comment]
Are you using the actual build process? Everything is done inside a container, so every build should be exact and pristine. @ibuildthecloud has a really nice Dockerfile.dapper process.

**Comment by deitch** [comment]
Hey @ibuildthecloud , if you get this pull in, you get RancherOS on your Surface Pro!

**Comment by ibuildthecloud** [comment]
@deitch that's some good motivation.  With the flurry of activity for v0.5 I have had time to review this, but I will try to get to it soon.

**Comment by deitch** [comment]
You getting me a Surface Pro is motivation? Sure! :-)

Seriously, I have not had much time to deal with it myself. I am prepping for my presentation at ContainerCon Japan next month, took up a *lot* more time than I thought to prepare. Something about wanting to have the entire performance test regimen to be a single github repo so anyone could replicate it. 

After you get it pulled, then we need to get `ros install` working (in my spare time?).

**Comment by deitch** [comment]
So 0.5.0 is out. Merging this in?

**Comment by jeff-h** [comment]
@deitch in case it's useful to know, I have just successfully used your image from https://github.com/rancher/os/pull/938#issuecomment-223801629 to startup rancheros from a USB stick on a Cenovo Mini PC 2 (e.g. http://www.gearbest.com/tv-box-mini-pc/pp_349864.html).

**Comment by deitch** [comment]
Excellent @jeff-h! I'm just waiting for the team to pull. It has been open for months.

**Comment by jeff-h** [comment]
Yes — a little frustrating to see that this is now marked v0.6.0 (referring to the end of https://github.com/rancher/os/issues/844).

Don't suppose you have any suggestions for how I could use your ISO to actually install a usable RancherOS onto my little PC? :)

Also — thanks hugely for your work on all this... I've read both the original issue and this PR from top to bottom and it was definitely quite an ordeal! Also, as I'm sure you know, the biggies (e.g. Ubuntu) still haven't sorted out the whole 64 bit OS with 32 bit uefi situation, despite the popularity of these really cheap (and seemingly, quite good) Atom-based systems. So you're leading the pack :)

**Comment by deitch** [comment]
> now marked v0.6.0

I missed that comment. Oh. I put the work into it back when 0.4.0 was the latest. Sigh. 

> thanks hugely for your work

:-)

> you're leading the pack

Thanks! I know at least one guy over at coreos, and he is wicked smart, much better at this than I. I leveraged his work to do the secure appliance build. 

> definitely quite the ordeal

All of this started as for a client, but became unnecessary, so it was labour of love. If I really am leading, maybe I should go work for one of them. Tell them to call me and make an offer. ;-)

**Comment by jeff-h** [comment]
Heheh, I wish they would make you an offer! :)

Are you saying CoreOS has a uefi ISO? I couldn't find it, but that would be my second choice after RancherOS. I have more-or-less resigned to Ubuntu Server for now, as there are instructions on how to get that installed on my system.

**Comment by deitch** [comment]
No they don't, not yet as far as I know. But the guy there is wicked smart. I like what they have done. I wrote a blog post about the innovation in OSes in last few years, specifically cited rancher, core, smartos

**Comment by deitch** [comment]
And since I'm an independent consultant, for last decade, I'd be happy to get offers. Nice thing about the flexibility.

**Comment by deitch** [comment]
@ibuildthecloud should I bother bumping this?

**Comment by SvenDowideit** [comment]
@deitch yes please :)

**Comment by ibuildthecloud** [comment]
@deitch.  Yes please!   I'd love to merge this.

**Comment by deitch** [comment]
@ibuildthecloud: Hey Darren, welcome back. I was in your neck of the woods for meetings last week, wanted to say hello and meet in person, emailed Dave G, never heard back. Any chance you/team will be at LinuxCon/ContainerCon Berlin next week?

So, yes, I am willing to fix this. But I need to know it will be merged in. It was a lot of work to get it right the first time half a year ago, and if I am about to put in the hours to get it right for whichever version, it has to be worthwhile.

Tell me that we will merge it when we rebase it?

If so, also tell me what branch/version I should sync it against?

**Comment by ibuildthecloud** [comment]
@deitch Yes it will be merged.  So either you can rebase or fix it up or if it's too much effort for you at this time then we can carry the PR and take over the work.  The end result is we are very serious about getting EFI support in and this PR is the first step.

I believe we will be at LinuxCon/ContainerCon but I'm not going myself.

**Comment by ibuildthecloud** [comment]
@deitch It looked like it was a simple rebase, so I went ahead and did that in https://github.com/rancher/os/pull/1262.  I'll test it out and if it seems good we'll merge.  I have a couple EFI systems I can try it on.

**Comment by ibuildthecloud** [comment]
@deitch It looked like it was a simple rebase, so I went ahead and did that in https://github.com/rancher/os/pull/1262.  I'll test it out and if it seems good we'll merge.  I have a couple EFI systems I can try it on.

**Comment by deitch** [comment]
@ibuildthecloud I will miss seeing you there. I heard from some of your people that you will have people there, but no one I know, unfortunately.

**Comment by deitch** [comment]
So #1262 is this identical PR but based off of the latest (looks like it since it is against `rancher:master`). On the other hand, it doesn't quite look like the PR is against my branch, but rather against `ibuildthecloud/os:pr938-rebase`. 

I don't mind if it is against your repo, but I will be unable to do any changes or patches that way.

I have some UEFI hardware dedicated to a project (of which this PR was an offshoot), so I will test against it too.

**Comment by ibuildthecloud** [comment]
@deitch Yes, that PR is just a rebase (notice you're still the author of the commit). I'd prefer to merge your PR, especially if you have more changes. I just did that in case you don't have time to do this.  We very much want EFI support.

**Comment by deitch** [comment]
Got it. Ok I'll merge rebase this PR, then redo the tests. I have the hardware ready for it. 

Hope I'll have time between work to get the install version working as well, but one step at a time.

**Comment by deitch** [comment]
Well, feh. Apparently I can change the base branch to `master`, but I cannot change the `from` branch, which was based upon `v0.5`. How messy. I think I need to do a whole new PR for this. I will make one more attempt to rebase my `v0.5` and rename it properly (not sure what possessed me _not_ to do so from the beginning), and if not, close this and open a new PR.

**Comment by deitch** [comment]
Yes, sigh, I must. Well, I will reference this PR anyways.

**Comment by deitch** [comment]
Closed in favour of open PR https://github.com/rancher/os/issues/1263 which is properly rebased.

**Comment by deitch** [comment]
Moving all comments to there.

**Pull request closed without merging**
