### PR TITLE
Fixed serial console login did not work on Online.net and it daughter …

### PR DESCRIPTION
**Pull request by tetatetit**
…Scaleway.com but shown garbage and broken futher output instead

### CODE REVIEW

**Comment by tetatetit** [comment]
If necessary  - I can provide screenshots or video how console looked in original rancher version in my online.net server

**Comment by SvenDowideit** [comment]
I wonder if this will cause trouble on some other systems - sadly, i don't have enough test gear to know

**Comment by SvenDowideit** [comment]
@tetatetit what consoles have you tested this with? each of them has a different getty/agetty iirc, and so we need to make sure it works ok with all of them

I've been wondering if we can remove the getty and sshd from the console, and move them into a system container that we can control. That would mean the user's console choice has fewer side effect too.

**Comment by tetatetit** [comment]
> what consoles have you tested this with? each of them has a different getty/agetty iirc, and so we need to make sure it works ok with all of them

It's agetty from os-base. Isn't it hardcoded in console_init.go, i.e. same for all console images available via `ros console switch`? Actually I just noticied that ubuntu, coreos (did not made deeper investigation) do not specify bitrate arg in agetty run and their console works perfectly everywhere, including Online.net console too. Or do you know the case/reasone why/wnen bitrate should be specified for agetty? At least I saw recommendation to specified different bitrates from lower to higher in turn although not sure why if ubuntu does not specify it at all.

> I've been wondering if we can remove the getty and sshd from the console, and move them into a system container that we can control. That would mean the user's console choice has fewer side effect too.

It's right idea indeed, IMO, but you guys should better  know whether it worth efforts for now and what priority to give for it. My fix solves real problem (not sure why nowhere else it encountered) with almost ( 99%) guaranty it will not cause any side affect since ubuntu/coreos (and most probable other) launch agetty without bitrate arg. Sorry and correct me please if I miss something

**Comment by SvenDowideit** [comment]
see #1234 - depending on which console you have loaded, a different agetty gets used.

**Comment by SvenDowideit** [comment]
@tetatetit what console did you test with?

**Comment by tetatetit** [comment]
agetty default one from os-base, but command line args for it I have changed and started to work with Online.net - I have comparted with official ubuntu distro/installation (I mean if to install and run ubuntu just as normal OS not as console image in rancher)

**Comment by SvenDowideit** [comment]
the getty that's being run is _not_ the one in the os-base - its the one in the selected console - which is why I'm wanting to know which console you're using to test - whatever changes we make atm, will need to be tested in each of the consoles that can be selected.

**Comment by tetatetit** [comment]
Yep, I used one from default console included in initrd, i.e. from os-console docker image which is based on os-base (i.e. buildroot's one that's why I meant it is from os-base because deault ininird's os-console does not contain own agetty but uses one from os-base which is based on builtroot in turn. Is it exactly what you would like to know? Sorry if I am not so clear in my answers

**Comment by tetatetit** [comment]
But I can test with all other consoles (centos, ubuntu, debian) if everything works the same. But just repeating that current command line args for agetty (i.e. what I fixed) are default for standard ubuntu installation by standard ubuntu distro instraller. And I think if bitrate in agetty command line args would be important - I think standard ubuntu installation would did it. Also now I clearly see your idea to always use same agetty from same docker image regardless of chosen console is it buildroot > os-base > os-console or ubuntu or something also. And I think yes, it would be great idea to maximize compatibility and minimize testings

**Comment by SvenDowideit** [comment]
darn, looks like this doesn't help with

running `read -p 'hit enter'` on `./scripts/run --fresh --append "rancher.debug rancher.console=alpine"`

@tetatetit   Very much looking forward to hearing if your change works one online.net for all the consoles

**Comment by SvenDowideit** [comment]
I've just come across a reproducable case - so I should now be able to test what this PR does when using the other consoles.

**Comment by SvenDowideit** [comment]
this change doesn't fix the problem in the qemu case - so I'm going to try some other things

**Comment by SvenDowideit** [comment]
without autologin

[rancher@rancher-dev ~]$ setserial -G
BusyBox v1.25.0 (2016-11-22 02:52:15 UTC) multi-call binary.

Usage: setserial [-gabGvzV] DEVICE [PARAMETER [ARG]]...

Request or set Linux serial port information

	-g	Interpret parameters as list of devices for reporting
	-a	Print all available information
	-b	Print summary information
	-G	Print in form which can be fed back
		to setserial as command line parameters
	-z	Zero out serial flags before setting
	-v	Verbose

Parameters: (* = takes an argument, ^ = can be turned off by preceding ^)
	*port, *irq, *divisor, *uart, *baud_base, *close_delay, *closing_wait,
	^fourport, ^auto_irq, ^skip_test, ^sak, ^session_lockout, ^pgrp_lockout,
	^callout_nohup, ^split_termios, ^hup_notify, ^low_latency, autoconfig,
	spd_normal, spd_hi, spd_vhi, spd_shi, spd_warp, spd_cust

UART types:
	unknown, 8250, 16450, 16550, 16550A, Cirrus, 16650, 16650V2, 16750,
	16950, 16954, 16654, 16850, RSA, NS16550A, XSCALE, RM9000, OCTEON, AR7,
	U6_16550A
[rancher@rancher-dev ~]$ 
[rancher@rancher-dev ~]$ 
[rancher@rancher-dev ~]$ stty
speed 9600 baud; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-brkint ixoff -imaxbel
-iexten -echoctl

**Pull request merged**
