### PR TITLE
docker-1.9

### PR DESCRIPTION
**Pull request by imikushin**
DON'T MERGE. Waiting for docker-1.9.1

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
@mailq Unfortunately you can't use 1.9 to build RancherOS that has 1.9 in it :disappointed:   https://github.com/docker/docker/issues/17290  There is a bug in 1.9.0 that fails for us.

**Comment by ibuildthecloud** [comment]
@imikushin I'm not so confident on 1.9 quite yet.  I'm trying to find out when 1.9.1 will be out.

**Comment by imikushin** [comment]
@mailq @ibuildthecloud That bug is pretty nasty. Otherwise, I'd use 1.9.0 instead of 1.8.3 in Dockerfile.build-base if it were not for the following problem: 

With docker 1.9 in our build container, the CI build fails on Drone, which apparently has Docker 1.8.
This is happening, because we do not run Docker-in-Docker. In our build container we're using the outside docker server by bind-mounting /var/run/docker.sock

**Comment by imikushin** [comment]
I'd also like to wait for 1.9.1. Let's hold it off.

**Comment by imikushin** [comment]
Mergin' it so we can cut v0.4.1 RC with docker 1.9

**Pull request merged**
