### PR TITLE
Add latest and running

### PR DESCRIPTION
**Pull request by SvenDowideit**
output:

```
RancherOS rancher-dev ttyS0
eth0: 10.0.2.15 lo: 127.0.0.1
rancher-dev login: rancher (automatic login)

INFO[0006] RancherOS c19f189-dirty started              
[rancher@rancher-dev ~]$ sudo ros os list
rancher/os:v0.6.1 remote latest 
rancher/os:v0.6.0 remote available 
rancher/os:v0.5.0 remote available 
rancher/os:v0.4.5 remote available 
rancher/os:v0.4.4 remote available 
rancher/os:v0.4.3 remote available 
rancher/os:v0.4.2 remote available 
rancher/os:v0.4.1 remote available 
rancher/os:v0.4.0 remote available 
c19f189-dirty running
[rancher@rancher-dev ~]$ 
```

(I'm not sure if "installed" or "running" is the right thing to say)

the first commit comes from #1271 - I'm presuming that can be merged first.

This PR relates to #147 and #148

### CODE REVIEW

**Comment by joshwget** [comment]
It's not really necessary for this PR, but reversing the order of the releases might be a nice addition. Putting the current version at the top might be nice too.

On a somewhat related topic, I don't really like the `ros os` subcommand in general. It seems like both words basically mean the same thing and it's only used for `ros os upgrade` and `ros os list`. I think this made more sense when it was `rancherctl os ...` and then when we moved to `ros` it was never updated.

Instead, maybe we could just move `ros os upgrade` to `ros upgrade` and include `ros os list` functionality in `ros version`. It's not a perfect fit for `ros version`, but I think it might be preferable to what we currently have.

**Comment by SvenDowideit** [comment]
OI, you! @joshwget that's a separate issue :p.

I've created you #1274

wrt reverse ordering, yup, we can do that, but the currently running version will be at the end if its not in the list that we request :)

**Comment by SvenDowideit** [comment]
updated with reverse order, and using `running` instead of `installed`

**Comment by joshwget** [comment]
LGTM

**Pull request merged**
