### PR TITLE
Gratuituous use of ASCII art on console

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

```


               ,        , ______                 _                 _____ _____
  ,------------|'------'| | ___ \               | |               /  _  /  ___|
 / .           '-'    |-  | |_/ /__ _ _ __   ___| |__   ___ _ __  | | | \ '--.
 \/|             |    |   |    // _' | '_ \ / __| '_ \ / _ \ '__' | | | |'--. \
   |   .________.'----'   | |\ \ (_| | | | | (__| | | |  __/ |    | \_/ /\__/ /
   |   |        |   |     \_| \_\__,_|_| |_|\___|_| |_|\___|_|     \___/\____/
   \___/        \___/     Linux 4.8.11-rancher

         RancherOS rancher-dev ttyS0
         docker-sys: 172.18.42.2 eth0: 10.0.2.15 lo: 127.0.0.1
rancher-dev login: rancher (automatic login)

```

### CODE REVIEW

**Comment by joshwget** [comment]
Can we take the `/` out of `Rancher/OS`?

**Comment by SvenDowideit** [comment]
but i likes it :p

**Comment by vincent99** [comment]
@smw355 will not be happy with any form of cow that isn't the standard right-facing logo one...

**Comment by flaccid** [comment]
This is a hi-value, contentious ticket. I agree with @joshwget though, it should be 'RancherOS'. I hope that is/ok.

**Comment by SvenDowideit** [comment]
@smw355 will need to make an ascii art standard right-facing cow!

**Comment by aemneina** [comment]
```
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                   `                                                                                    
                                                                                                                     ;                                             `;                                   
                                                                                                                    ;';                                            ;''                                  
                                                                                                                    '''                                            '''                                  
                                                                                                                   ;'''                                            '''`                                 
                                                                                                                   ;'''                                            ''''                                 
                                                                                                                   ''''                                            ''''                                 
                                                .;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:     ;;'';;;;;;;;;;;;;;;;;;;;;;;;;;;;':`             ''''                                 
                                              `;'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''    ''''''''''''''''''''''''''''''''''''            ''''                                 
                                              ,'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  ,''''''''''''''''''''''''''''''''''';'          `''''                                 
                                              ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  '''''''''''''''''''''''''''''''''''''',         ;'''',                                
                                             '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  '''''''''''''''''''''''''''''''''''''''         ;'''';                                
                                            ,;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  '''''''''''''''''''''''''''''''''''''';       .'''''''                                
                                            ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''':  '''''''''''''''''''''''''''''''''''''''  ,,,;'''''''';                                
                                           ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''`  '''''''''''''''''''''''''''''''''''''''  '''''''''''';                                
                                          .'';'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  .'''''''''''''''''''''''''''''''''''''''  ''''''''''';'                                
                                          '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''   '''''''''''''''''''''''''''''''''''''''  '''''''''''''                                
                                         ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''   '''''''''''''''''''''''''''''''''''''''  ''''''''''';'                                
                                        `;'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''    ''''''''''''''''''''''''''''''''''''''  ''''''''''''                                 
                                        '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''     :''''''''';'.''''''''''''''''''''''''  '''''''''',                                  
                                       ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''                 ;;'''''''''''''''''''''''                                               
                                      `;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''`              ;'''''''''''''''''''''''''                                               
                                      ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''                                               
                                     ;;'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''';'''''''''''';''''''''''''''''''''''''''                                               
                                    `'''''';;::;'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''                                               
                                    ;'''''';` ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''                                               
                                   ;'''''';   ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''                                               
                                    ';''';    ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''                                               
                                     ''',     ;'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''';'''''''''''''''''''''''                                               
                                     .'`      ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''';' ''''''''''''''''''''''''                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''` ''''''''''''''''''''''''                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  ''''''''''''''''''''''''                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  ''''''''''''''''''''''''                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  ''''''''''''''''''''''''                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  ''''''''''''''''''''''''                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  ''''''''''''''''''''''''                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  ''''''''''''''''''''''''                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  ''''''''''''''''''''''''                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  ''''''''''''''''''''''''                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  ''''''''''''''''''''''''                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  ''''''''''''''''''''''''                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''  ,'''''''''''''''''''';;`                                               
                                              ;''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''   ''''''''''''''''''''':`                                               
                                              ;'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''';'''''''';    ,''''''''''''''';';.                                                 
                                              ;'''''''''''''''''''''''';...........................................:''''''''''''                                                                        
                                              ;'''''''''''''''''''';''                                               ''''''''''''                                                                       
                                              ;'''''''''''''''''''''';                                               `'''''''''';;;.`````````                                                           
                                              ;'''''''''''''''''''''',                                                ';'''''''''''''''''''''                                                           
                                              ;'''''''''''''''''''''',                                                '''''''''''''''''''''''                                                           
                                              ;'''''''''''''''''''''',                                                '''''''''''''''''''''''                                                           
                                              ;'''''''''''''''''''''',                                                '''''''''''''''''''''''                                                           
                                              ;'''''''''''''''''''''',                                                '''''''''''''''''''''''                                                           
                                              ;'''''''''''''''''''''',                                                '''''''''''''''''''''''                                                           
                                              ;'''''''''''''''''''''',                                                '''''''''''''''''''''''                                                           
                                              ;'''''''''''''''''''''',                                                '''''''''''''''''''''''                                                           
                                              ;'''''''''''''''''''''',                                                '''''''''''''''''''''''                                                           
                                              ;'''''''''''''''''''''',                                                '''''''''''''''''''''''                                                           
                                              ;'''''''''''''''''''''',                                                '''''''''''''''''''''''                                                           
                                              ;'''''''''''''''''''''',                                                '''''''''''''''''''''''                                                           
                                              ;'''''''''''''''''''''',                                                ;''''''''''''''''''''';                                                           
                                              :'''''''''''''''''''''',                                                ''''''''''''''''''''';'                                                           
                                               ;'''''''''''''''''''';                                                 '''''''''''''''''''''';                                                           
                                               :'''''''''''''''''''',`                                                 '''''''''''''''''''''                                                            
                                               `                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
OR                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXWMMMMMMMMMMMMMMMMMMMMNXNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMWWMMWWWWWMXodNWWWMMMMMMMMWWMMMMMMM0lkWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWKdooooooooooooooooooooooodooddoooxXO::odoooooooooooodkKWMMMO:oXMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNkc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,cOx;;;,;;;;;;;;;;;;;;dXK0kl;:0MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMXd:,;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;,oKx;;;;;;;;;;;;;;;;;;dkc;;;;cOMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWKo;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;lOOxdddddc;;;;;;;;;;,oK0OOOOKNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWOc;:ol;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;:::::::;;,,;;;;;;;,oNMWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWOox0Nk;;;;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:c;,;;;;;;;;,oNWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWWMMWk;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;okc,;;;;;;;;;oNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWk;;;;;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;,;,dkc;;;;;;;;;;oNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMk;;;;;;;;;;,;;;,;;,,,,,,,,,,,,,,,,;;;;;;;d0l;,;;,;;;;;xWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWk;;;;;;;;;,;lxxxxxxxxxxxxxxxxxxxxxxxo:;;;ckOxxxxxkkkk0NMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMk;;;;;;;;;;c0MMMMMMMMMMMMMMMMMMMMMMMXo;;;;;cllllxNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMk;;;;;;;;;;lKMMMMMMMMMMMMMMMMMMMMMMMNd;;,;;;;;;;oXMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMk;;;;;;;;;;cKMMMMMMMMMMMMMMMMMMMMMMMNd;;;;;;;;;,oNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWOc;;;;;;;;;oKMMMMMMMMMMMMMMMMMMMMMMMNx;;;;;;;;;;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNK000000000XWMMMMMMMMMMMMMMMMMMMMMMMWNK00000000KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
                                                                                                                                                                                                       
                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        

```

**Comment by aemneina** [comment]
One at 80 chars wide
```
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXWMMMMMMMMMMMMMMMMNNWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWNXXXXXXXXXXXXXXXXXXXXXXXXXNWkl0XXXXXXXXXXXNWWMWkoKMMMMMMMMMMMM
MMMMMMMMMMMMMMMMW0l:cc::ccccccccccccccccccc:d0o;:ccccc:::cccl0WWXo:OMMMMMMMMMMMM
MMMMMMMMMMMMMMMNk:,;;;;;;;;;;;;;;;;;;;;;;;;,oOl,;;;;;;;;;;;;;xklc;;xWMMMMMMMMMMM
MMMMMMMMMMMMMWXd:;;;,;;;;;;;;;;;;;;;;;;;;;;;lOxooooc;;;;;;;;;x0kkkOXWMMMMMMMMMMM
MMMMMMMMMMMMMKo:oo:;;;;,;;;;;;;;;;;;;;;;;;;;;;:::::;;;;;;;;;;kWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMX00NKc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,:l:,;;;;;;;kWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMKc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;cxl,;;;;;;;kWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMKc;;;;;;;;;,;;;,,,,,,,;;;;;;;;;;;cko;;;;;;;:OWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMKc;;;;;;;:okOOOOOOOOOOOOOOOOOkl;;;okdooxOOOKWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMKc,;;;;;;c0MMMMMMMMMMMMMMMMMMWx;;;;;;;;dNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMKc;;;;;;,c0MMMMMMMMMMMMMMMMMMWk;;;;;;;,dNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMKo::::;:;lKMMMMMMMMMMMMMMMMMMWOc:::;:::xWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWWNKKKKKKKXWMMMMMMMMMMMMMMMMMMMNXKKKKKKKNMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
```

**Comment by vincent99** [comment]
Those are a tad big..  @lvuch can probably do some better hand-tweaking...

```
               /\      /\
  ,------------|'-----\'| ______                 _                 _____ _____
 / .           '-`    |-  | ___ \               | |               /  _  /  ___|
 \/|             |    |   | |_/ /__ _ _ __   ___| |__   ___ _ __  | | | \ '--.
   |             `----`   |    // _' | '_ \ / __| '_ \ / _ \ '__' | | | |'--. \
   |   .________.   |     | |\ \ (_| | | | | (__| | | |  __/ |    | \_/ /\__/ /
   |   |        |   |     \_| \_\__,_|_| |_|\___|_| |_|\___|_|     \___/\____/ 
   \___/        \___/     Linux 4.8.10-rancher
```

**Comment by aemneina** [comment]
^^ that looks like a winner @vincent99

**Comment by joshwget** [comment]
We could always have the login message dynamically pull in comments from this PR :shipit:

**Comment by ibuildthecloud** [comment]
On a related note
```
 ________________________________________
/ I've always felt like RancherOS should \
\ include cowsay                         /
 ----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

**Comment by ibuildthecloud** [comment]
```

                          ______                 _                 _____ _____
  ,------------|'-----\'| | ___ \               | |               /  _  /  ___|
 / .           '-`    |-  | |_/ /__ _ _ __   ___| |__   ___ _ __  | | | \ '--.
 \/|             |    |   |    // _' | '_ \ / __| '_ \ / _ \ '__' | | | |'--. \
   |   .________.`----`   | |\ \ (_| | | | | (__| | | |  __/ |    | \_/ /\__/ /
   |   |        |   |     \_| \_\__,_|_| |_|\___|_| |_|\___|_|     \___/\____/ 
   \___/        \___/     Linux 4.8.10-rancher
```

@vincent99 I think it's better without `/\`

**Comment by vincent99** [comment]
Fair enough, it can shift up a line then to match the text

**Comment by ibuildthecloud** [comment]
I'm looking for a better font now http://www.figlet.org/examples.html

**Comment by janeczku** [comment]
```                                                                                                                                                   
 ________                    ______             _______________       
 ___  __ \_____ ________________  /_______________  __ \_  ___/       
 __  /_/ /  __ `/_  __ \  ___/_  __ \  _ \_  ___/  / / /____ \        
 _  _, _// /_/ /_  / / / /__ _  / / /  __/  /   / /_/ /____/ /        
 /_/ |_| \__,_/ /_/ /_/\___/ /_/ /_/\___//_/    \____/ /____/         
 Linux 4.8.10-rancher                                                 
```

The font is named "speed". Seemed fitting.

**Comment by joshwget** [comment]
I think I actually vote for having just an ASCII cow. "RancherOS" in ASCII art reminds me too much of MS Word art and seems a bit tacky.

**Comment by janeczku** [comment]
```                                                                                                     
                         ▦▦           ▦▦▦▦           
     ▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦          
    ▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦ ▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦          
  ▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦    ▦▦▦▦▦▦▦▦▦ ▦▦            
  ▦▦▦ ▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦               
      ▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦               
      ▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦ ▦▦▦▦▦▦▦▦               
      ▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦ ▦▦▦▦▦▦▦               
      ▦▦▦▦▦▦▦              ▦▦▦▦▦▦▦                   
      ▦▦▦▦▦▦▦              ▦▦▦▦▦▦▦                   
      ▦▦▦▦▦▦▦              ▦▦▦▦▦▦▦                   
      RancherOS v0.7.1                               
```

**Comment by vincent99** [comment]
@joshwget hasn't spent enough time on BBSes 😛

**Comment by SvenDowideit** [comment]
@vincent99 shifting up the cow looks like

```
  ,------------|'------'| ______                 _                 _____ _____
 / .           '-`    |-  | ___ \               | |               /  _  /  ___|
 \/|             |    |   | |_/ /__ _ _ __   ___| |__   ___ _ __  | | | \ '--.
   |   .________.`----`   |    // _' | '_ \ / __| '_ \ / _ \ '__' | | | |'--. \
   |   |        |   |     | |\ \ (_| | | | | (__| | | |  __/ |    | \_/ /\__/ /
   \___/        \___/     \_| \_\__,_|_| |_|\___|_| |_|\___|_|     \___/\____/
                          Linux 4.8.10-rancher
```

**Comment by SvenDowideit** [comment]
@vincent99 @ibuildthecloud  - adding a `.` as the tip of the horns:

```
               .        . ______                 _                 _____ _____
  ,------------|'-----\'| | ___ \               | |               /  _  /  ___|
 / .           '-`    |-  | |_/ /__ _ _ __   ___| |__   ___ _ __  | | | \ '--.
 \/|             |    |   |    // _' | '_ \ / __| '_ \ / _ \ '__' | | | |'--. \
   |   .________.`----`   | |\ \ (_| | | | | (__| | | |  __/ |    | \_/ /\__/ /
   |   |        |   |     \_| \_\__,_|_| |_|\___|_| |_|\___|_|     \___/\____/
   \___/        \___/     Linux 4.8.10-rancher
```

**Comment by rfranke** [comment]
The "logo" doesn't show up when ssh'ing into the machine. Should it?

**Comment by SvenDowideit** [comment]
its not "usual" for the issue file to be shown for ssh - but I may make it happen if we extract the sshd from the console containers and into its own container.

**Comment by vincent99** [comment]
Needs **moo**re /etc/motd.

**Comment by flaccid** [comment]
+1 for sshmoo.

**Comment by SvenDowideit** [comment]
```


               ,        , ______                 _                 _____ _____
  ,------------|'------'| | ___ \               | |               /  _  /  ___| TM
 / .           '-'    |-  | |_/ /__ _ _ __   ___| |__   ___ _ __  | | | \ '--.
 \/|             |    |   |    // _' | '_ \ / __| '_ \ / _ \ '__' | | | |'--. \
   |   .________.'----'   | |\ \ (_| | | | | (__| | | |  __/ |    | \_/ /\__/ /
   |   |        |   |     \_| \_\__,_|_| |_|\___|_| |_|\___|_|     \___/\____/
   \___/        \___/     Linux 4.8.11-rancher

         RancherOS rancher-dev ttyS0
         docker-sys: 172.18.42.2 eth0: 10.0.2.15 lo: 127.0.0.1
rancher-dev login: rancher (automatic login)

```

**Pull request merged**
