### PR TITLE
bump to docker-1.10.1

### PR DESCRIPTION
**Pull request by imikushin**
bump to docker-1.10.1

### CODE REVIEW

**Comment by thaJeztah** [comment]
\o/

**Comment by imikushin** [comment]
@thaJeztah I hope that doesn't mean "Please, don't do that!"

**Comment by thaJeztah** [comment]
@imikushin haha, no, it was me cheering! :-)

**Comment by imikushin** [comment]
k, mergin' :)

**Comment by thaJeztah** [comment]
:tada: sorry for scaring you, haha

**Comment by imikushin** [comment]
I'm releasing RancherOS v0.4.3 now :)

**Comment by thaJeztah** [comment]
Congrats!

**Comment by imikushin** [comment]
Thanks! It's out :fireworks:

**Pull request merged**
