### PR TITLE
Disable docker server TLS cert auto-generation

### PR DESCRIPTION
**Pull request by imikushin**
Disable docker server TLS cert auto-generation

Because users should be explicit about their docker TLS certs.

Also, write the key and cert files when `ros tls gen` is run

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
@imikushin Can you make passing certs in the cloud-config on boot work also.  Also this PR needs a rebase.

**Comment by imikushin** [comment]
Updated. Keys and certs from cloud-config will get written to files in `/etc/docker/tls` on docker system service start if rancher.docker.tls is true.

**Comment by joshwget** [comment]
Can you add an integration test with `rancher.docker.tls` true in the cloud config?

**Comment by imikushin** [comment]
@joshwget You were right: I added the test and found a bug! Now it's good to go.

**Pull request merged**
