### PR TITLE
WIP: Refactored RPI building scripts and support for Raspberry Pi 3

### PR DESCRIPTION
**Pull request by DieterReuter**
Building a SD image for the Raspberry Pi ARMv7 based models:
* supports Raspberry Pi 2 B
* supports Raspberry Pi 3 B

Note: as soon as we do have an ARMv6 compatible RancherOS rootfs, we can support all old Pi models as well.

The build process fetches the Hypriot kernel package for the Raspberry Pi, install it on a clean directory and upgrades the bootfiles to support the brand-new Raspberry Pi 3 B. As we currently don't support ARMv6 for RancherOS, this kernel files will be deleted in order to save disk space. As result we're getting a compress ZIP archive with 46MByte only. The sizes of boot and root partitions can be customised in the `build.sh` script.

Known issues on Pi 3:
* serial UART console doesn't work
* no support for internal WiFi/BT

### CODE REVIEW

**Comment by DieterReuter** [comment]
Just for everybody who wants to try RancherOS on a Pi2 or Pi3, here is a SD image for download https://downloads.hypriot.com/rancheros-rpi2-20160307.zip.

Ping @luxas.

**Comment by ibuildthecloud** [comment]
@DieterReuter Thanks!  I'm going to merge and we can keep iterating on this.

**Comment by DieterReuter** [comment]
:tada:

That's a great plan.

**Comment by zimme** [comment]
Playing around with this now, got it up and running, working on expanding the fs over the whole sdcard =) then I'll try and get rancher running on it too.

**Pull request merged**
