### PR TITLE
Logrotate. Issue #329

### PR DESCRIPTION
**Pull request by konstruktoid**
Daily rotation of /var/log/messages and /var/log/*docker*
Issue  #329 "Rotate /var/log/messages"

The indentation is wrong, so could you tell which settings I should use?

Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
The formatting is based off of gofmt.  So just do `gofmt -w yourfile.go` and it will format it correctly.

**Comment by konstruktoid** [comment]
Thanks @ibuildthecloud, correct formatting applied in https://github.com/konstruktoid/os/commit/0af9437c4d9bb0375b4dc0b0d46f3ce7b8b47ae6

**Comment by ibuildthecloud** [comment]
@konstruktoid We want to include this in v0.4.0.  We have done a major refactor in v0.3.2 for the packaging of RancherOS.  If you want we can carry forward these patches for you and refactor it as needed for the new build structure.

**Comment by konstruktoid** [comment]
Sure thing @ibuildthecloud, sounds great. Do you want me to do something?

**Comment by ibuildthecloud** [comment]
Nope, we'll take it from here.  We'll keep the PR open.

**Comment by imikushin** [comment]
continued in rancher/os-images#16, #484

**Pull request closed without merging**
