### PR TITLE
Detect hypervisor and start its driver service plus vmware cloud-init datasource

### PR DESCRIPTION
**Pull request by SvenDowideit**
This change will detect `vmware` (auto aliased to `open`), `kvm`, `hyperv`, `xenhvm` and `bhyve`, during the init process, and will add `rancher.services_include.<vmname>-vm-tools=true` to the cfg before the main os containers are started.

This will cause those yml files to be requested from the core repo, and if they exist (only `open-vm-tools` does atm) will pull the image and start the service.

this means that with docker-machine v0.12 and later, you can successfully do 

```
(I have my vsphere auth settings in my env)

~/bin/machine -D create --driver vmwarevsphere \
	--vmwarevsphere-vcenter 10.10.10.2 \
	--vmwarevsphere-boot2docker-url rancheros.iso \
        machine-name
```

### CODE REVIEW

**Comment by SvenDowideit** [comment]
and as an extra bonus: 

```
[root@detect docker]# system-docker exec -it open-vm-tools vmware-rpctool 'info-get guestinfo.rancher.test'
sven
```

So I'm going to look at adding this to a the config settings - i'm no t100% sure i can get it to happen before the `cloud-init-save`, but ideally, it should be used in a way that's similar to the kernel boot cmdline - to prime the config.

**Comment by SvenDowideit** [comment]
unlike the cloud-init based systems, RancherOS doesn't get access to the open-vm-tools until after the OS has finished booting. So we can't use it to modify settings / trigger an install during the first boot.

One way to get around this is to use the config-2 cloud-init CDROM (ala openstack).

But, what I can do, is add some post processing to the `open-vm-tools` service to grab guestinfo, then merge it into the existing config and reboot.

for example, if `guestinfo.rancher.cloud_init.datasources=[url:http://arian/cloud-init.yml]` is defined in the vmware guest info, that cloud-init would be active during the second boot phase.

**Comment by SvenDowideit** [comment]
see https://github.com/docker/machine/pull/4143 too

**Comment by SvenDowideit** [comment]
And this latest commit adds full onboot cloud-init-save datasource `vmware`

either set `guestinfo.cloud-init.config.data` with base64 encoded cloud-init data, or set `guestinfo.cloud-init.config.url` with a cloud-init file url.

**Comment by prologic** [comment]
Does this also detect Proxmox VE? (KBM based hypervisor)?

**Pull request merged**
