### PR TITLE
Only cache service definitions

### PR DESCRIPTION
**Pull request by joshwget**
#1300

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM

**Comment by SvenDowideit** [comment]
I kinda feel we should revisit this entirely

**Comment by joshwget** [comment]
@SvenDowideit Sounds good.

**Comment by joshwget** [comment]
@SvenDowideit Thinking about reopening this. I don't think we'll have time for a comprehensive refactoring of services before v0.8.0 and AFAIK this is strictly better than current caching.

**Comment by SvenDowideit** [comment]
I feel I'd get confused if we cache some things, and not others - perhaps the quick change we can do is to add an `--invalidate-cache` that removes all cached files (i'm assuming that once a service is enabled, we're storing that cfg elsewhere - like in the config?

**Comment by SvenDowideit** [comment]
yes, reopening for discussion

**Comment by joshwget** [comment]
The only two things that are cached right now are service definitions and the os-services index.yml. Essentially, this PR just removes the latter from being cached. If I was a user I think I'd be more confused by this behavior than only caching service definitions.

**Comment by SvenDowideit** [comment]
As a user, I'm confused about how, or when I get an updated service definition.

**Comment by joshwget** [comment]
Definitely agree the story around updating a service config is confusing. This PR shouldn't change anything around that though. The only thing this does is stop caching things that shouldn't be cached.

**Comment by joshwget** [comment]
Changing my mind on this one again. I'd rather think about this more.

**Pull request closed without merging**
