### PR TITLE
run the iso

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

because i have a lack of trust :)

mmm, I have some other changes to this script stashed somewhere.

### CODE REVIEW

**Comment by joshwget** [comment]
I'm actually not sure what the purpose of this is. Is there some advantage to testing with the ISO?

**Comment by SvenDowideit** [comment]
Yes, I use it to test the entire boot cycle, and added it because I was getting different results to what the kernel boot was giving me.

**Comment by joshwget** [comment]
I'm a little hesitant to add more to the already massive `scripts/run`. But I also think this has the potential to replace `scripts/create-installed` once we embed the installer in the ISO.

**Comment by SvenDowideit** [comment]
I'll be adding more to it - including a `--machine` - I want a consistent way we can test all the modes.

**Pull request merged**
