### PR TITLE
Import docs for vnext

### PR DESCRIPTION
**Pull request by SvenDowideit**
This should allow us to create PR's that contain both code and docs updates - which should make it easier for us to review the UX impact.

When we make a release, we can make a PR to the `rancher/rancher.github.io` repo 
(and yes, we'll need to make sure we don't loose fixes that are made there)

### CODE REVIEW

**Comment by SvenDowideit** [comment]
BTW - I test this not by installing Jekyll and ruby, but by adding a github pages setting to my fork - that way the rendering is done by github.

**Comment by joshwget** [comment]
@SvenDowideit Jekyll is a pain. Rendering this with Github would be awesome to document.

**Comment by SvenDowideit** [comment]
and boom, we have `make docs`

**Comment by joshwget** [comment]
Even better!

**Pull request merged**
