### PR TITLE
Configure DNS nameservers with DHCP or cloud-config

### PR DESCRIPTION
**Pull request by imikushin**
Allow network service to automatically configure DNS from DHCP (by default). 
This can be overridden and configured with values from cloud-config.

### CODE REVIEW

**Comment by imikushin** [comment]
Should fix #339. 

This is WIP, because it's based on not yet merged PR #659.

**Comment by imikushin** [comment]
Oh, and this needs rancher/netconf#3

**Comment by deniseschannon** [comment]
https://github.com/rancher/os/issues/451

**Comment by qrpike** [comment]
Still having this issue.

**Comment by dszryan** [comment]
using version 0.4.2
i have set nameservers and override via ros (confirmed values are written in clould-config.yml)
but the values in resolv.conf are still dhcp server values, even after reboot or sudo netconf

and unable to resolve domain names
image

image

**Comment by qrpike** [comment]
@dszryan I had the same issues and literally just spend all night trying to get it working. Ended up having to put the cloud-config.yml as a write-file. Inception basically. Example:

https://gist.github.com/qrpike/cfd5245d4459a2d6efd8

Pretty hacky and I don't like it at all, but it's the cleanest thing I could come up with. I've tried about everything lol

**Comment by dszryan** [comment]
i swapped over from docker itself, coz of this issue.... 
and this wasnt an issue v0.4.1, i am rolling back to the older version until its fixed

**Comment by mtrofimm** [comment]
@qrpike do you if it's possible to include dynamic some dynamic param into var/lib/rancher/conf/cloud-config.yml?
something like: $(wget -O- http://169.254.169.254/current/meta-data/local-ipv4 into eth1 address?

**Comment by djmaze** [comment]
Having the same problems. I don't know how this could even work with DHCP. The DHCP client (`dhcpcd`) is running in the background all the time, overwriting any values set manually in resolv.conf. 

As far as I can see, the client's configuration (`dhcpcd.config`) has to be adjusted for this to work as well. Using `nooption domain_name_servers, domain_name, domain_search` or similar.

**Pull request merged**
