### PR TITLE
Test verbosity

### PR DESCRIPTION
**Pull request by tetatetit**
Output names of test funcs, otherwise impossible to say what exactly test failed on 'integration-test' and quite difficult on 'test' script

### CODE REVIEW

**Comment by joshwget** [comment]
For some reason unit tests are being skipped after this addition. We'll have to figure out why this is the case before merging.

**Comment by tetatetit** [comment]
Just unit? With integration-test all is ok? Can't be related to resent change
```
if [ "$ARCH" = "amd64" ]; then
    RACE="-race"
fi
```

**Comment by joshwget** [comment]
Just unit tests. If only `-v -check.vv` is removed then everything seems to work fine again, so I think it is related to this PR.

**Comment by SvenDowideit** [comment]
@tetatetit when I run `make test` with your change, I get:

```
 ---> 5acdd3f6a573
Removing intermediate container a5dbf0a25887
Successfully built 5acdd3f6a573
Running tests
?       github.com/rancher/os   [no test files]
INFO[0040] docker cp /go/src/github.com/rancher/os/bin .
INFO[0040] docker cp /go/src/github.com/rancher/os/dist .
INFO[0040] docker cp /go/src/github.com/rancher/os/build/initrd build
sven@i7:~/src/rancher/os-delete$
```

If I remove your change, I get:

```
Removing intermediate container c8824b469d2d
Successfully built 15973ca4b604
Running tests
?       github.com/rancher/os   [no test files]
?       github.com/rancher/os/cmd/cloudinitexecute      [no test files]
?       github.com/rancher/os/cmd/cloudinitsave [no test files]
?       github.com/rancher/os/cmd/cloudinitsave/gce     [no test files]
ok      github.com/rancher/os/cmd/control       1.022s  coverage: 1.0% of statements
?       github.com/rancher/os/cmd/control/service       [no test files]
?       github.com/rancher/os/cmd/control/service/app   [no test files]
?       github.com/rancher/os/cmd/control/service/command       [no test files]
?       github.com/rancher/os/cmd/network       [no test files]
?       github.com/rancher/os/cmd/power [no test files]
?       github.com/rancher/os/cmd/respawn       [no test files]
?       github.com/rancher/os/cmd/sysinit       [no test files]
?       github.com/rancher/os/cmd/systemdocker  [no test files]
?       github.com/rancher/os/cmd/wait  [no test files]
?       github.com/rancher/os/compose   [no test files]
ok      github.com/rancher/os/config    1.118s  coverage: 35.9% of statements
?       github.com/rancher/os/config/yaml       [no test files]
?       github.com/rancher/os/dfs       [no test files]
?       github.com/rancher/os/docker    [no test files]
?       github.com/rancher/os/hostname  [no test files]
?       github.com/rancher/os/init      [no test files]
?       github.com/rancher/os/log       [no test files]
?       github.com/rancher/os/netconf   [no test files]
?       github.com/rancher/os/scripts   [no test files]
?       github.com/rancher/os/selinux   [no test files]
ok      github.com/rancher/os/util      1.010s  coverage: 14.4% of statements
ok      github.com/rancher/os/util/network      1.058s  coverage: 0.0% of statements
INFO[0026] docker cp /go/src/github.com/rancher/os/bin .
INFO[0027] docker cp /go/src/github.com/rancher/os/dist .
INFO[0027] docker cp /go/src/github.com/rancher/os/build/initrd build
sven@i7:~/src/rancher/os-delete$
```

**Comment by SvenDowideit** [comment]
replaced by #1718

**Pull request closed without merging**
