### PR TITLE
Support NFS shares in cloud-config mounts

### PR DESCRIPTION
**Pull request by janeczku**
https://github.com/rancher/os/issues/1620

### CODE REVIEW

**Comment by SvenDowideit** [comment]
I'm presuming this change makes the following work?

```
#cloud-init
rancher:
 mounts:
    - ["${efs_server}:/", "/mnt/efs", "nfs4", "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"]
```

**Comment by SvenDowideit** [comment]
we should work out a way to get this tested regularly :/

**Comment by janeczku** [comment]
> I'm presuming this change makes the following work?
@SvenDowideit correct. Should work both with fs-type `nfs` and fs-type `nfs4`.

**Comment by gizmotronic** [comment]
Oddly enough, I can use nfs4 mounts without this change.

**Comment by SvenDowideit** [comment]
@janeczku can you confirm that #1506 fixes it for you?

**Comment by SvenDowideit** [comment]
@janeczku I'm going to close this on the assumption that #1506 resolves this too

**Comment by bott0r** [comment]
Coming back to this. Without a nfs client i can just mount via a simple line:
`sudo mount -t nfs4 192.168.0.2:/mnt/volume01/data /mnt/data`

However when i translate thet line to a cloudconfig with either:

```
#/var/lib/rancher/conf/cloud-config.d/z.yml
mounts:
- ["192.168.0.2:/mnt/volume01/data", "/mnt/data", "nfs4", ""]
```
or with

`ros config set mounts '[["192.168.0.2:/mnt/volume01/data", "/mnt/data1", "nfs4", ""]]'`

it just doesnt work, what am i missing, i crawled by now through the documentation that is available or cached 404 pages, along side closed github issues. does anyone have a pointer here?

**Comment by niusmallnan** [comment]
Ping @kingsd041 , can you make a regression test about this？

@bott0r which documentation? https://rancher.com/docs/os/v1.x/en/installation/storage/additional-mounts/ ?

**Comment by kingsd041** [comment]
@bott0r Which version of RancheOS are you using? V1.5.0-rc1?

**Comment by bott0r** [comment]
> @bott0r Which version of RancheOS are you using? V1.5.0-rc1?
Yep
```
[rancher@beta ~]$ sudo ros os version
v1.5.0-rc1
[rancher@beta ~]$

```

**Pull request closed without merging**
