### PR TITLE
check the validity of the console name

### PR DESCRIPTION
**Pull request by datawolf**
Signed-off-by: Wang Long long.wanglong@huawei.com

### CODE REVIEW

**Comment by SvenDowideit** [comment]
do we need some way to accept a Console image name that was built locally (for testing, or some debug reason)?

**Comment by joshwget** [comment]
@SvenDowideit The validation here is more about name of the service rather than the name of the console image.

There are two cases that this PR doesn't handle.
- Service definition hosted at a given URL: `ros console switch https://raw.githubusercontent.com/rancher/os-services/master/u/ubuntu.yml`
- Service definition locally on disk: `ros console switch /var/lib/rancher/conf/ubuntu.yml`

If the service name is a valid URL or path, we should skip validation. It's exactly the same for engines and pretty similar for generic services.

**Comment by SvenDowideit** [comment]
@joshwget do we have tests for that? :)

**Comment by SvenDowideit** [comment]
@datawolf thank you for the contribution - its prompted @joshwget's #1433 :)

**Pull request closed without merging**
