### PR TITLE
Change host engine opt type to list

### PR DESCRIPTION
**Pull request by joshwget**
#1347

### CODE REVIEW

**Comment by SvenDowideit** [comment]
so how are we handling the transition from old string based host settings to the new array?

**Comment by joshwget** [comment]
It's handled automatically in `os-config.yml` when that's updated. For user settings it'll have to be manually upgraded.

**Comment by SvenDowideit** [comment]
its for the user that i'm worried about - is there any way we can start having versioned yml files?

**Comment by joshwget** [comment]
Versioning configuration was something I was planning on doing post-GA. I think it'd be a pretty large effort for now.

**Pull request merged**
