### PR TITLE
Add upgrade flag to upgrade persistent console

### PR DESCRIPTION
**Pull request by joshwget**
Adds the flag `upgrade-console` to `ros os upgrade`. This will set the new config flag `force_console_rebuild`, which will force a console rebuild on next boot. After rebuilding the console, the flag is set back to false.

### CODE REVIEW

**Comment by liyimeng** [comment]
Do we migrate data from old container if a force rebuild to happen?

**Comment by joshwget** [comment]
No, this should only be used if you're willing to part ways with your data :smile:

**Comment by liyimeng** [comment]
@joshwget OK, might be useful in a dev environment.

**Comment by deniseschannon** [comment]
https://github.com/rancher/os/issues/855

**Pull request merged**
