### PR TITLE
GPT partition option

### PR DESCRIPTION
**Pull request by konsumer**
This adds a `-g` flag to select gptmbr.bin for MBR image, allowing installation on a GPT harddrive.

I'm really not sure how to test it, but if someone can explain it to me, I'd be happy to test.

### CODE REVIEW

**Comment by joshwget** [comment]
@konsumer I think this needs a rebase to build successfully.

**Comment by konsumer** [comment]
Happy to do this once I get home. It was merging clean before, maybe a new change?  Any ideas on how to actually test it? I have a harddrive I am fine with formatting.

**Comment by konsumer** [comment]
In [the log](https://drone.rancher.io/rancher/os/404) it looks like ` RUN if [ -n "${!KERNEL_URL}" ]; then         curl -fL ${!KERNEL_URL} > ${DOWNLOADS}/kernel.tar.gz` is failing, which is unrelated to my changes (as far as I can tell.) Am I misreading this?

**Comment by joshwget** [comment]
No, you're correct that it's not related to this PR. That problem is fixed in master so a rebase should fix it :smile:

**Comment by konsumer** [comment]
sweet! I will update tonight when I get home.

**Comment by SvenDowideit** [comment]
mmm, I'm tempted to merge this, and then import the bits into my re-write - but i need to get a test disk setup (i'm not at home until mid-next week - and my 3TB disks are all there)

**Comment by SvenDowideit** [comment]
mmm, VBox only lets me make disks up to 2TB :( going with VMWare :D

**Comment by konsumer** [comment]
Hehe, yeh that was the issue I was having with testing. How do we add a flag to `ros install`?

**Comment by SvenDowideit** [comment]
I'll add the flags in #1456 - but initially, its possible to use the installer container directly - annoyingly the first test i did had issues with the partitions i'd set up :)

**Comment by SvenDowideit** [comment]
What I'm trying:
* [ ] replace fdisk with parted
* [ ] convert the use of parted to gpt

# using parted manually, and then continuing the install manually
```
parted /dev/vda mklable msdos
parted -s -a optimal /dev/vda mklabel gpt -- mkpart primary ext4 1 -1
mkfs.ext4 -F -i 4096 -L RANCHER_STATE /dev/vda1
system-docker run --rm -it --net host --privileged --volumes-from=user-volumes --volumes-from=command-volumes zombie/os:64ec90f -d /dev/vda -t noformat --a "rancher.autologin=tty1"
```

**Comment by SvenDowideit** [comment]
wow. the number of times I forgot to push the zombie/os:.. image and then had to do it again :(

**Comment by SvenDowideit** [comment]
@konsumer can you please merge https://github.com/konsumer/os/pull/1 - it contains changes to make it possible to use your changes :)

after that, I'll merge this PR, and then apply the changes to #1456 - and then @deitch and I can work on getting UEFI and gpt support done.

The gptsyslinux install works, and boots from the 4TB disk - but its not mounted and used - so more work is needed.

**Comment by deitch** [comment]
Hey @SvenDowideit definitely glad to see this come back to life. I know what needs to be done, happy to finally bring this to a close, both for booting live UEFI and for `ros install`. Let me know when we are at a point to bring it in and I will reopen the PR on latest base.

**Comment by konsumer** [comment]
I finally had some time to try it out and got a "Missing OS" error. Can anyone tell what I did wrong?

I decided to make a 100GB partition for state, and give the rest of the 4TB to media storage.

```
sudo parted -s -a optimal /dev/sda mklabel GPT mkpart primary ext4 1 100GB
sudo parted -s -a optimal /dev/sda -- mkpart primary ext4 100GB -1
sudo parted /dev/sda set 1 boot on
sudo mkfs.ext4 -F -i 4096 -L RANCHER_STATE /dev/sda1
sudo mkfs.ext4 -F -i 4096 -L MEDIA -m 0 /dev/sda2
sudo system-docker run --rm -it --net host --privileged --volumes-from=user-volumes --volumes-from=command-volumes zombie/os:64ec90f -d /dev/sda -t noformat -a "rancher.autologin=tty1"
```

I used [this cloud-config.yml](https://gist.github.com/konsumer/dd52196b31a8c3d0aff66f38ef461f72).

Then ran this:

```
sudo ros install -d /dev/sda -c cloud-config.yml --no-reboot -i zombie/os:64ec90f -t gptsyslinux -f
```

On reboot it won't boot.

**Pull request merged**
