### PR TITLE
Top level cloud config

### PR DESCRIPTION
**Pull request by tetatetit**
ALL top level cloud-config keys as kernel args work now if prefixed with "cc.", while prefixed just with "rancher." works as well for legacy backward compat. cc.ssh_authorized_keys='["ssh_rsa foopubkey foo@bar.com"]' works well now with #1439 which assumed to be applied first

### CODE REVIEW

**Comment by joshwget** [comment]
Can you remove the first commit? It's already in #1439 and then we could merge this PR first.

**Comment by tetatetit** [comment]
> Can you remove the first commit? It's already in #1439 and then we could merge this PR first.

Removed

**Comment by joshwget** [comment]
LGTM! The prefix `cc.` could be better, but I think it's okay for now. We can always change it later.

**Comment by tetatetit** [comment]
> cc. could be better

Sorry if I miss something, but isn't it exactly `.cc` in my PR?

**Comment by tetatetit** [comment]
Is any more action from my side expected to get this PR merged?

**Comment by joshwget** [comment]
It is `cc.` in your PR, which I think is okay for now. Just waiting on another LGTM from @SvenDowideit or @ibuildthecloud.

**Comment by tetatetit** [comment]
Sorry, I just misstyped while meant cc. , i.e cc.ssh_authorized_keys , cc.hostname , cc.rancher.state.dev etc., while just top level e.g. rancher.state.dev works as well for backward compatibility. So I am still does not see how it differs from what you said:

> The prefix cc. could be better

**Comment by SvenDowideit** [comment]
LGTM! sorry, distracted :(

**Pull request merged**
