### PR TITLE
Add auditd

### PR DESCRIPTION
**Pull request by adampointer**
Preliminary work as discussed in #1849. Depends on adding audit to the packages manifest in the buildroot config in the `rancher/os-base` repo. For now we just download the tarball from the releases in our fork. Obviously this needs changing. Also pretty sure my changes to `scripts/layout` are sub-optimal!

### CODE REVIEW

**Comment by SvenDowideit** [comment]
You're going to hate me, but - this needs some docs telling users what it does, what they can do with it, and probably, how to turn it off.

**Comment by adampointer** [comment]
Ok! Will get it after the long weekend (UK bank holiday Monday 😊). Where do you want the docs? Yeah actually I agree, we need to include at least the basic docker audit rules for this and an off switch.

**Comment by adampointer** [comment]
I have added some cloud-config to configure and disable the daemon. Still unsure about where you want docs to live.

**Comment by SvenDowideit** [comment]
@adampointer sorry, distracted by vmware work

if you put the docs anywhere under `docs/os`, I'll wire it up afterwards. most of it is to help me and others work out what you intended, so we can play along when the time comes.

**Pull request closed without merging**
